### ISSUE TITLE
I made a simple and crude game controlled by jarvis

### ISSUE THREAD

**Issue by carlcc** [fiatrete/OpenDAN-Personal-AI-OS#10]
https://youtu.be/ZfOoBG0QX0s

[![screenshot](https://github.com/fiatrete/OpenDAN-Personal-AI-OS/assets/12776190/b797d9c7-6619-4235-ba79-48be470317fd)](https://youtu.be/ZfOoBG0QX0s)

Hi,

The other day, I found jarvis is interesting. Thus I made a simple game to interact with jarvis.

Yeah, indeed it is a crude demo game, but it's really funny to play in such way, it's a completely different experience.

After inserting a speech2text process by using a certain input method, it's even more interesting.

I hope you guys will like it!

Here is the source code: https://github.com/carlcc/MyJarvis/

**Comment by fiatrete** [comment]
Great job! I discovered two interesting scenarios from your video. One is using Jarvis to control IoT smart devices at home, such as lights, TV, and air conditioning. Another intriguing scenario is playing games with Jarvis, like building a world in Minecraft, where we provide guidance while Jarvis handles the execution. It sounds like a lot of fun just thinking about it!

**Comment by DiligentCatCat** [comment]
Cool. I would even better if your game is made by a web-base engine, that would be much easier to let other people play your game
