### ISSUE TITLE
How to extend functions when users define agents in the new version

### ISSUE THREAD

**Issue by wugren** [fiatrete/OpenDAN-Personal-AI-OS#114]
In the old version, Agent can define environment.py to extend functions, but it seems that the relevant logic is not seen in the new version.

**Comment by waterflier** [comment]
In the current version, the logic for extending functions has undergone a fundamental change. The functions expanded by the Agent are usually composed of underlying functions, while the expansion of native functions typically implies an increase in system's native capabilities, which will be more cautious (involving permission and privacy control). In the future, extensions will be made through the Plugin system.

**Comment by waterflier** [comment]
You can read this : https://github.com/fiatrete/OpenDAN-Personal-AI-OS/blob/MVP/doc/function_list.md  for more about "System AI Functions"

**Comment by wugren** [comment]
> In the current version, the logic for extending functions has undergone a fundamental change. The functions expanded by the Agent are usually composed of underlying functions, while the expansion of native functions typically implies an increase in system's native capabilities, which will be more cautious (involving permission and privacy control). In the future, extensions will be made through the Plugin system.

Does composed of underlying functions mean letting AI generate the code that calls the underlying function? I'm still a little worried about the current AI's ability to generate code. It may not be able to generate it correctly.

**Comment by waterflier** [comment]
It is definitely dangerous to rely entirely on AI's ability to write code, so we can divide Agents into two categories: one is an Agent that only uses existing functions in combination, and the other is an Agent that allows it to write code when necessary. I am very much looking forward to seeing the comparison of the capabilities of these two agents in real scenarios.

In fact, in the past 8 weeks of development, I have felt great uncertainty in high-dimensional LLM calls, and I am thinking about how to share these experiences with everyone.

**Comment by wugren** [comment]
I don't expect to use AI to generate a lot of code, I just followed your reply above. My question is, as an agent developer, what should you do when you need to expand functions?
ps：the Plugin system you mentioned has not been implemented yet.

**Comment by waterflier** [comment]
We've also upgraded the Function and Action capabilities in version 0.5.2. I will be drafting a detailed document later to introduce these enhancements. I believe this will address most of your concerns and provide deeper insights into the improvements made in this release.
