### ISSUE TITLE
The project hasn't been updated for a long time, and is it still being maintained?

### ISSUE THREAD

**Issue by So-Far-So-Good** [fiatrete/OpenDAN-Personal-AI-OS#123]
The project hasn't been updated for a long time, and is it still being maintained?

**Comment by waterflier** [comment]
We are always updating on the MVP branch （https://github.com/fiatrete/OpenDAN-Personal-AI-OS/tree/MVP）

The current version (0.5.2) hopes to build a universal Knowledge base (RAG). Judging from the current practice, the difficulty exceeds our expectations. I am still continuing to try various different routines and hope to get more people. advice and help.

Thanks for your attention~
