### ISSUE TITLE
The 1660 graphics card does not work well with local sd

### ISSUE THREAD

**Issue by lowkeywx** [fiatrete/OpenDAN-Personal-AI-OS#2]
My laptop configuration： 
Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.60 GHz
16.0 GB (15.9 GB 可用)
nVidia 1660

System Info：
Windows 11 home
22H2

I've deployed stable-diffusion-webui locally.  Use the following command to start: `python launch.py --share --api` .  Set the value  `DEMO_STABLE_DIFFUSION_ADDRESS=<sd share url>` in  `docker/jarvis/.env` .  When I was running autotest in webset, the cpu, memory and hard disk usage was 100%.

**Comment by fiatrete** [comment]
How much is your GPU memory ? Depending on the specific model you are using, Stable Diffusion can consume between 4GB and 10GB of video memory. So, you may need a more powerful graphics card.

Certainly, you can also optimize it by following these methods:
1. use `--xformers` when startup Stable Diffusion webui
2. set `"enable_hr": Fasle,` in `stable_diffusion.module.py` to disable upscale
