### ISSUE TITLE
OpenAI’s 0613 updates seems awesome

### ISSUE THREAD

**Issue by fiatrete** [fiatrete/OpenDAN-Personal-AI-OS#22]
OpenAI just pushed out their 0613 updates, now rocking support for 'functions'. This is huge! It's going to make the Agent's call to functional modules much easier and make the function calls more stable. I'm stoked about this and can't wait to revamp Jarvis's code using this new 'functions' style. Hang tight, I should have this ready for you in a couple of days.

The AI community is moving really fast. Just when I thought I could take a breather and get my head around the AI OS architecture, this thrilling update comes out of nowhere. And this update coincides with my understanding of the separation of intelligence and computing. I believe the open source LLM community will quickly catch up with support for functions, even whipping out specialized models optimized just for functions.

**Comment by DiligentCatCat** [comment]
Yeah, I have simply tested it, the new `function` API is great! It's result is much more stable.

We can employ this API for current implementation, I think this makes sense.

**Comment by maxwilliamdev** [comment]
This is a very important feature, it provides better instruction-level operation for LLM. Machines need to collaborate with each other, and the LLM update is a middleman between machine and human.

**Comment by codemanship** [comment]
Can't wait the new version!!!

**Comment by Synthintel0** [comment]
Can't wait the new version!!!

**Comment by fiatrete** [comment]
The code is out! Feel free to checkout and have fun with it!

**Comment by Anon2578** [comment]
Do you guys have a discord for this project ?
