### ISSUE TITLE
Let's start the development of the MVP！

### ISSUE THREAD

**Issue by waterflier** [fiatrete/OpenDAN-Personal-AI-OS#27]
I think I cann't wait your guys complete the DAO Page of opendan~  
In the meantime, we can start development of the OpenDAN MVP version in parallel.

The MVP goal of OpenDAN is to help people build their own knowledge base in the AI era, and based on this to support future AI Agents running on OpenDAN, the main process is as shown in the diagram.

<img width="1482" alt="procedures" src="https://github.com/fiatrete/OpenDAN-Personal-AI-OS/assets/1612159/7220d4f2-c4fa-4f80-b021-6c312fb0ab2f">

I think we can achieve this goal through two main versions:

Step 1: Change the way people search/browse personal information, and further change the way data is stored. 
1. A better "resource manager": information manager (library) to replace the file system. 
2. Provide a conversational product for searching and browsing personal information. 
3. Through Functions expansion, allow AI Agent (possibly using cloud-based LLM kernel) to do more personalized work using KB.

Step 2: Establish a personal (information, device) center with the participation of AI Agent. Strengthen the "accessibility" and usability of personal (information/capabilities). (Read-only -> Read-write) The personal center becomes the "personal homepage" in the AI+Web3 era.

Could you please create a new branch for MVP ~  I will commit more documents through Pull Request.

**Comment by fiatrete** [comment]
Done!

**Comment by waterflier** [comment]
Simple but useful ^_^~

**Comment by waterflier** [comment]
PR is here : https://github.com/fiatrete/OpenDAN-Personal-AI-OS/pull/28
