### ISSUE TITLE
Calling for the moudle-PM of the MVP!

### ISSUE THREAD

**Issue by waterflier** [fiatrete/OpenDAN-Personal-AI-OS#29]
Thanks to fiatrete, we can start developement of OpenDAN mvp at brach : https://github.com/fiatrete/OpenDAN-Personal-AI-OS/tree/MVP

Based on the rules design of the upcoming SourceDAO, next step we need to 

1. Confirm the version leader (I recommend myself) 
2. Calling for the moudle-PM (you will receive OpenDAN DAO Token rewards after the version is released!) The first version of MVP is 0.5.1, I have submitted the basic design document, check it here https://github.com/fiatrete/OpenDAN-Personal-AI-OS/blob/MVP/doc/mvp/mvp%20plan.md
3. You can apply to become the moudle-PM in this issue, or discuss how the design (including difficulty design) of certain modules should be more reasonable. When applying, if you're willing, you can introduce yourself a bit~

*The following content is from MVP document. (https://github.com/fiatrete/OpenDAN-Personal-AI-OS/blob/MVP/doc/mvp/mvp%20plan.md)  I have extracted some important content related to the application for the module-PM*

# OpenDAN Basic Planning of MVP 
0.5.1 Implement data capture into Knownlege-Base(KB) via Spider, followed by access by AI Agent  (35%)
0.5.2 Build a Personal-Center based on the KB and associate the AI Agent with accessible telgram accounts (30%)
0.5.3 Release for waitlist （5%）
0.5.4 First public release (10%)
0.5.5 Incorporate modifications after the first public version, workload depends on feedback (15%)
0.5.6 Official version of MVP (5%)

# R&D Process Management
Based on the project management module provided by SourceDAO, explore a new open source R&D process of "open source is mining".
0. Confirming Version Leader based on committee election.
1. Module (task division): Divide the system's futures into independent modules as much as possible, the development workload should be at the level of 1 person for 2-3 weeks.
2. Discussion: Discuss whether the module division is reasonable, and design it's *BUDGET* based on the difficulty of the module and its importance to the current version (most important step)
3. Recruit module PM. The module PM is responsible for the module's test delivery: completing the set functions, constructing the basic tests, and passing the self-tests. Testing should retain at least 30% of development resources.
4. For the completed module, PM should write and publicize the Project Proposal. It contains more detailed about module goals + design ideas, participating teams (if any, there should also be a preliminary division of work within the team and calculation of contribution value), and acceptance plan design.
5. The PM completes development and self-testing. Mark the module is *DONE*.
6. Version Leader organizes the acceptance of the module (a dedicated acceptor can be appointed).
7. Version Leader organizes integration testing according to the completion situation, and the module PM fixes BUGs. The test results can be used in the nightly-channel of OpenDAN.
8. After the test passes, the Version Leader announces the version release, anyone can use this from release-chanel.
9. The committee accepts the version after the release effect. After acceptance, all participants can extract contribution rewards.

Difficulty is expressed in the mode of requirement engineer level * time (in weeks, less than 1 week is counted as 1 week). 1 week of work time is calculated as 20 hours.

**Comment by wugren** [comment]
Many ideas about AI in the document are very similar to current mainstream AI libraries, such as Langchain. However, the main goal of these libraries is to make AI better at solving problems, not to create a user-friendly product. We can directly integrate such a library and transform it into a personal AI OS, making it convenient for users to use.

**Comment by glen0125** [comment]
Hi, I'm very interested in this idea and would like to start with **LLM Kernel Packaging**. Afterwards, I'll attempt to engage in the development of more modules. Is the goal of LLM Kernel Packaging to abstract LLMs into several unified interfaces for agents or humans to call?

**Comment by streetycat** [comment]
> 

I think, we can define the interfaces between modules, and implement them with exist libs. and update it in future if it's necessary.

**Comment by streetycat** [comment]
> Many ideas about AI in the document are very similar to current mainstream AI libraries, such as Langchain. However, the main goal of these libraries is to make AI better at solving problems, not to create a user-friendly product. We can directly integrate such a library and transform it into a personal AI OS, making it convenient for users to use.

I think, we can define the interfaces between modules, and implement them with exist libs. and update it in future if it's necessary.

**Comment by alexsunxl** [comment]
Looks good

**Comment by waterflier** [comment]
> Many ideas about AI in the document are very similar to current mainstream AI libraries, such as Langchain. However, the main goal of these libraries is to make AI better at solving problems, not to create a user-friendly product. We can directly integrate such a library and transform it into a personal AI OS, making it convenient for users to use.

LangChain, with its MIT license, is a well-known framework with many concepts that align closely with ours. Its main goal is to build an AI-accessible KnowledgeBase, which is only a part of OpenDAN's functionality.

OpenDAN's objective is to facilitate the private deployment of AI Agents. Based on my past experience, this private deployment is not limited to a single user host but extends to a private cluster composed of multiple user devices. This implies that some services/functions might not run on the same host as the Agent. The operation of the KnowledgeBase could also be coordinated across multiple devices.

LangChain's implementation does not seem to abstract this kind of environment, which suggests that using LangChain directly might not fulfill OpenDAN's goals. However, we could start by abstracting key concepts from the perspective of OpenDAN's objectives. In the early stages, we could get some modules running based on LangChain, and gradually replace them as needed.

**Comment by wugren** [comment]
> > Many ideas about AI in the document are very similar to current mainstream AI libraries, such as Langchain. However, the main goal of these libraries is to make AI better at solving problems, not to create a user-friendly product. We can directly integrate such a library and transform it into a personal AI OS, making it convenient for users to use.
> 
> LangChain, with its MIT license, is a well-known framework with many concepts that align closely with ours. Its main goal is to build an AI-accessible KnowledgeBase, which is only a part of OpenDAN's functionality.
> 
> OpenDAN's objective is to facilitate the private deployment of AI Agents. Based on my past experience, this private deployment is not limited to a single user host but extends to a private cluster composed of multiple user devices. This implies that some services/functions might not run on the same host as the Agent. The operation of the KnowledgeBase could also be coordinated across multiple devices.
> 
> LangChain's implementation does not seem to abstract this kind of environment, which suggests that using LangChain directly might not fulfill OpenDAN's goals. However, we could start by abstracting key concepts from the perspective of OpenDAN's objectives. In the early stages, we could get some modules running based on LangChain, and gradually replace them as needed.

Langchain's primary work is the implementation and encapsulation of AI-related operations. We need the parts that overlap with our goals from it, and of course, anything not available would require us to develop ourselves. This includes operations like Embedding, AI inference, Memory, LLM encapsulation, Tools, etc. In Langchain, these modules inter-depend on each other through abstract interfaces, and we have the freedom to define our own implementations as required.

For instance, if we want to deploy our local LLM to another server, all we need to do is extend an LLM class. Similarly, if we wish to apply permission restrictions to our Tools, such as running them in Docker or on another server, we only need to customize a BaseTool class.

This approach not only allows us to leverage industry's relatively advanced AI models but also enables us to focus more on our specialized goals, thereby greatly accelerating the achievement of our objectives.

And of course, we can ensure adequate isolation to conveniently replace with more advanced models in the future.

**Comment by lurenpluto** [comment]
After reading the code implementation of the existing OpenDAN and the architecture design of the new MVP, I feel it is very interesting, but from a personal point of view, there are still some questions
1. What is the relationship between the new architecture and the existing OpenDAN code implementation? Will it be developed on top of that or will it be a completely new architecture and impls? Will some components and designs be reused?
2. Is there any design specification, coding specification, etc. for the whole project? I have seen the new architecture diagram, but there are still some deficiencies in the actual development, such as some directory structure design, common components and so on, is there also a guideline specification and reference design?

**Comment by lurenpluto** [comment]
If possible, I'd consider providing a version of **Knowledge Base** design and development, as mentioned inside the MVP design above, consider providing multiple supported vector databases with possible access control (ACLs), and the low-level NON/NDN storage of CYFS that was previously developed may provide some help and development guidance

**Comment by wugren** [comment]
I would like to implement agent runtime module if possible

**Comment by waterflier** [comment]
> After reading the code implementation of the existing OpenDAN and the architecture design of the new MVP, I feel it is very interesting, but from a personal point of view, there are still some questions
> 
> 1. What is the relationship between the new architecture and the existing OpenDAN code implementation? Will it be developed on top of that or will it be a completely new architecture and impls? Will some components and designs be reused?
> 2. Is there any design specification, coding specification, etc. for the whole project? I have seen the new architecture diagram, but there are still some deficiencies in the actual development, such as some directory structure design, common components and so on, is there also a guideline specification and reference design?

I would like to share my perspective on the relationship between the Minimum Viable Product (MVP) and the current Network-on-Chip (NoC) in OpenDAN. I agree with many others that the current implementation of NoC makes OpenDAN look less like a system, which is precisely the role of the MVP.

1. In my view, following the MVP design, we should make use of the existing code where possible, and it won't be a big issue if it's not entirely usable. After all, OpenDAN is still in its early stages.

2. Currently, I am writing the initial system code for the MVP. My hope for the first version of the MVP is to translate more core concepts of the Personal AI Server OS from paper to code. I believe that the Python-based AI developer community already has many best practices. In terms of coding style and library usage, as long as it doesn't conflict with the architecture, it's acceptable. After all, completion is more important than perfection at this stage.

I appreciate your feedback and am happy to clarify any unclear aspects of my design. However, this issue might be getting too long, and it might be better to start a new one.

**Comment by waterflier** [comment]
I am writing a issue about the SourceDAO initial config of OpenDAN, and record all self-recommand from your guys~  speak is cheap ,let's code~  

 OpenDAN mvp is a large project, welcome!

**Comment by glen0125** [comment]
> Hi, I'm very interested in this idea and would like to start with **LLM Kernel Packaging**. Afterwards, I'll attempt to engage in the development of more modules. Is the goal of LLM Kernel Packaging to abstract LLMs into several unified interfaces for agents or humans to call?

Is there a more detailed documentation for this? I think we should initially create a typical use case, in which we can utilize all (or as many as possible) of the modules. Then, we can describe the workflow and how the modules interact with each other. This might help us better understand the entire design.

**Comment by alexsunxl** [comment]
Is the Email-Spider module a part  of the first MVP version? It should be relatively simple I think. 
And I would like to attempt to complete this part of the work.

**Comment by waterflier** [comment]
> 

Absolutely, take your time. I'm here to help whenever you're ready with the pseudocode for the key scenarios.

**Comment by streetycat** [comment]
Hello everyone, I am a rust programmer and I am currently learning AI knowledge. I want to participate in this project, I would like to try to complete the 'Compute Runtime' module.

**Comment by waterflier** [comment]
> 
This module is rename to Compute Node，in order to distinguish it from the app runtime. The design goal of the app runtime is isolation. In addition to isolation, the goal of the computing runtime is to efficiently utilize computing resources.
