### ISSUE TITLE
Discussion on the contribution rates of the NoC version’s contributors 

### ISSUE THREAD

**Issue by fiatrete** [fiatrete/OpenDAN-Personal-AI-OS#42]
As mentioned in issue #34, here are the contribution rates of the NoC version’s contributors from my point of view:

contributor | contribution rates
-- | --
@fiatrete | 45%
@maxwilliamdev | 20%
@troy6en | 10%
@DiligentCatCat | 10%
@Synthintel0 | 10%
@suntodai | 5%

Thank you for your contributions during the NoC phase. Please note that this is an approximate estimation as the nature and expertise required for tasks vary.

We started with a vague concept, and now the project's objectives are becoming clearer. A special shoutout to @troy6en, @Synthintel0, and @DiligentCatCat, who took on a significant amount of development work in addition to their full-time jobs. @maxwilliamdev has been an active community advocate, making outstanding contributions to the project's promotion in the AI community, and inspiring many creative ideas. And last but not least, @suntodai, a seasoned AI scientist, has provided invaluable advice for the project's evolution.

Please clearly reply to this issue with either 'agree' or 'disagree' to indicate your stance on the proposed contribution rate assessment. And attach your ETH address if you agree.

**Comment by fiatrete** [comment]
My eth address: 0x95809E7434e0350BDb59100e2DCBfCf7F885CFEC

**Comment by DiligentCatCat** [comment]
Agree. Mine: 0x480A6bB983f9cDEB7fAB1C9EeA3Df3951420926B

**Comment by Synthintel0** [comment]
I agree.
My eth address: 0xCE7E2d5C7eFC10960304DA879A9e0fB02c8b1713

**Comment by troy6en** [comment]
Agree.
My eth address: 0x51Ce0bcB8C1fd434b52Ecc14f211Ff35a117448C
