### ISSUE TITLE
Knowledge pipeline error - crash shell

### ISSUE THREAD

**Issue by smarath3** [fiatrete/OpenDAN-Personal-AI-OS#94]
Entered following command in the shell:
`/knowledge add email | dir`

and provided relevant inputs, and saw the crash (see snapshot)

Looks like a simple typo error (save_cosnfig instead of save_config), but thought important enough to fix since it crashes the shell, OS process altogether. I can try fixing it by submitting pull request later this week, but maybe someone at it can make a quick fix.

<img width="1040" alt="Screenshot 2023-11-07 at 10 39 46 AM" src="https://github.com/fiatrete/OpenDAN-Personal-AI-OS/assets/490406/5359db51-511e-4de6-b3c4-9686dd81dd12">

**Comment by photosssa** [comment]
Pipeline refactory is in process now, no more need to config email pipeline with shell interactions but config file. A new implement of email pipeline input will be merged soon.

**Comment by smarath3** [comment]
Thanks. Let me know (ETA) on when it'll be merged. Will keep an eye for testing! 
Closing this bug since refactor is in progress.
